/* sienaconf.h.  Generated by configure.  */
/*
** Siena configuration template
**
**  This file is part of Siena, a wide-area event notification system.
**  See http://www.cs.colorado.edu/serl/dot/siena.html
**
**  Author: Antonio Carzaniga <carzanig@cs.colorado.edu>
**  See the file AUTHORS for full details.
**
**  Copyright (C) 1998-1999 University of Colorado
**
**  This program is free software; you can redistribute it and/or
**  modify it under the terms of the GNU General Public License
**  as published by the Free Software Foundation; either version 2
**  of the License, or (at your option) any later version.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program; if not, write to the Free Software
**  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
**  USA, or send email to serl@cs.colorado.edu.
**
**
** $Id: sienaconf.in,v 1.1 2002/06/10 19:56:19 carzanig Exp $
*/
#ifndef _SIENACONF_H_
#define _SIENACONF_H_

#define SIENAVERSION "0.3.2"

/*
 *  types
 */
/* #undef socklen_t */
/* #undef uint32_t */
/* #undef in_addr_t */
/* #undef in_port_t */
/* #undef ssize_t */

/*
 *  macros
 */
/* #undef MAXHOSTNAMELEN */

/*
 *  have/don't have stuff
 */
/* #undef HAVE_SIZE_T */
/* #undef HAVE_SSIZE_T */

/* #undef HAVE_CXX_NAMESPACE */

#endif
