/* sienaserverconf.h.  Generated by configure.  */
/*
** Siena configuration template
**
**  This file is part of Siena, a wide-area event notification system.
**  See http://www.cs.colorado.edu/serl/siena/
**
**  Author: Antonio Carzaniga <carzanig@cs.colorado.edu>
**  See the file AUTHORS for full details.
**
**  Copyright (C) 1998-2002 University of Colorado
**
**  This program is free software; you can redistribute it and/or
**  modify it under the terms of the GNU General Public License
**  as published by the Free Software Foundation; either version 2
**  of the License, or (at your option) any later version.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program; if not, write to the Free Software
**  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
**  USA, or send email to serl@cs.colorado.edu.
**
**
** $Id: sienaserverconf.in,v 1.3 2002/06/12 22:36:05 carzanig Exp $
*/
#ifndef _SIENASERVERCONF_H_
#define _SIENASERVERCONF_H_

#define SIENASERVERVERSION "0.3.2"

/* #undef HAVE_CXX_NAMESPACE */

/* #undef HAVE_PID_T */
#define HAVE_GETDTABLESIZE 1
/* #undef HAVE_TIOCNOTTY */

#define HAVE_SETSID 1
#define HAVE_GETPGRP 1
/* #undef SETPGRP_VOID */

/*
 *  configuration flags
 */
/* #undef NO_THREADS */

#endif
